--- #YAML:1.0
name:               Alien-Jerl
version:            1.06
abstract:           mJERL is a mips compiled micro perl that runs in a JVM
author:
    - michaelt shomsky <17michaelt@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
